"""add post publication reseaux

Revision ID: 1bdd27df0330
Revises: 2f0a6013cfe2
Create Date: 2026-08-15 04:44:49.014327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdd27df0330'
down_revision: Union[str, Sequence[str], None] = '2f0a6013cfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_characters', sa.Integer(), nullable=False),
    sa.Column('api_base_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('reseaux_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', name='statuspublication'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['reseaux_id'], ['reseaux.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'reseaux_id', name='uq_post_reseau')
    )
    op.create_index(op.f('ix_publication_post_id'), 'publication', ['post_id'], unique=False)
    op.create_index(op.f('ix_publication_reseaux_id'), 'publication', ['reseaux_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_reseaux_id'), table_name='publication')
    op.drop_index(op.f('ix_publication_post_id'), table_name='publication')
    op.drop_table('publication')
    op.drop_table('reseaux')
    # ### end Alembic commands ###
