"""modification

Revision ID: d9db08a71d68
Revises: 1bdd27df0330
Create Date: 2026-08-17 17:21:02.432944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9db08a71d68'
down_revision: Union[str, Sequence[str], None] = '1bdd27df0330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('schedule_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('publication', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('publication', 'schedule_at')
    # ### end Alembic commands ###
